# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: spot_backend
    environment:
      - NODE_ENV=development
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db
    command: npm run dev
  db:
    image: mysql:5.7.13
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

 
#build: docker-compose build
#Run docker in detached mode
#docker-compose up -d
#docker-compose run --service-ports db


##jump into container
# docker exec -it 4bdefd5e5c3e mysql 

# docker system prune -a delete all containerinos

# docker build -t spot-backend .