# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: spot_backend
    environment:
      - NODE_ENV=development
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_NAME=spot_dev
      - DB_HOST=spot_local_db
    restart: always
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - db
    command: npm run dev
  db:
    image: mysql:5.7.13
    container_name: spot_local_db
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306


#build: docker-compose build
#Run docker in detached mode
#docker-compose up -d
#docker-compose run --service-ports db


##jump into container
# docker exec -it 4bdefd5e5c3e mysql

# docker system prune -a delete all containerinos

# docker build -t spot-backend .
