# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    container_name: node-app
    restart: always
    build: 
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - db
    command: npm run dev
  db:
    image: mysql:5.7.13
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

 
#Run docker in detached mode
#docker-compose up -d
#docker-compose run --service-ports db


# docker exec -it 4bdefd5e5c3e mysql 